export const banks: { code: string; name: string }[] = [
  { code: '560', name: 'Page MFBank' },
  { code: '304', name: 'Stanbic Mobile Money' },
  { code: '308', name: 'FortisMobile' },
  { code: '328', name: 'TagPay' },
  { code: '309', name: 'FBNMobile' },
  { code: '011', name: 'First Bank of Nigeria' },
  { code: '326', name: 'Sterling Mobile' },
  { code: '990', name: 'Omoluabi Mortgage Bank' },
  { code: '311', name: 'ReadyCash {code: Parkwa name:y)' },
  { code: '057', name: 'Zenith Bank' },
  { code: '068', name: 'Standard Chartered Bank' },
  { code: '306', name: 'eTranzact' },
  { code: '070', name: 'Fidelity Bank' },
  { code: '023', name: 'CitiBank' },
  { code: '215', name: 'Unity Bank' },
  { code: '323', name: 'Access Money' },
  { code: '302', name: 'Eartholeum' },
  { code: '324', name: 'Hedonmark' },
  { code: '325', name: 'MoneyBox' },
  { code: '301', name: 'JAIZ Bank' },
  { code: '050', name: 'Ecobank Plc' },
  { code: '307', name: 'EcoMobile' },
  { code: '318', name: 'Fidelity Mobile' },
  { code: '319', name: 'TeasyMobile' },
  { code: '999', name: 'NIP Virtual Bank' },
  { code: '320', name: 'VTNetworks' },
  { code: '221', name: 'Stanbic IBTC Bank' },
  { code: '501', name: 'Fortis Microfinance Bank' },
  { code: '329', name: 'PayAttitude Online' },
  { code: '322', name: 'ZenithMobile' },
  { code: '303', name: 'ChamsMobile' },
  { code: '403', name: 'SafeTrust Mortgage Bank' },
  { code: '551', name: 'Covenant Microfinance Bank' },
  { code: '415', name: 'Imperial Homes Mortgage Bank' },
  { code: '552', name: 'NPF MicroFinance Bank' },
  { code: '526', name: 'Parralex' },
  { code: '035', name: 'WemaBank' },
  { code: '084', name: 'Enterprise Bank' },
  { code: '063', name: 'Diamond Bank' },
  { code: '305', name: 'Paycom' },
  { code: '100', name: 'SunTrust Bank' },
  { code: '317', name: 'Cellulant' },
  { code: '401', name: 'ASO Savings and & Loans' },
  { code: '030', name: 'Heritage' },
  { code: '402', name: 'Jubilee Life Mortgage Bank' },
  { code: '058', name: 'GTBank Plc' },
  { code: '032', name: 'Union Bank' },
  { code: '232', name: 'Sterling Bank' },
  { code: '076', name: 'Skye Bank' },
  { code: '082', name: 'Keystone Bank' },
  { code: '327', name: 'Pagatech' },
  { code: '559', name: 'Coronation Merchant Bank' },
  { code: '601', name: 'FSDH' },
  { code: '313', name: 'Mkudi' },
  { code: '214', name: 'First City Monument Bank' },
  { code: '314', name: 'FET' },
  { code: '523', name: 'Trustbond' },
  { code: '315', name: 'GTMobile' },
  { code: '033', name: 'United Bank for Africa' },
  { code: '044', name: 'Access Bank' },
];
