// Authentication constants
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const FORGOT_PASSWORD_LOADING_INDICATOR = 'FORGOT_PASSWORD_LOADING_INDICATOR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'FAILURE';
export const LOGIN_LOADING_INDICATOR = 'LOGIN_LOADING_INDICATOR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_LOADING_INDICATOR = 'SIGNUP_LOADING_INDICATOR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_LOADING_INDICATOR = 'LOGOUT_LOADING_INDICATOR';

export const GET_2FA_REQUEST = 'GET_2FA_REQUEST';
export const GET_2FA_SUCCESS = 'GET_2FA_SUCCESS';
export const GET_2FA_FAILURE = 'GET_2FA_FAILURE';
export const GET_2FA_LOADING_INDICATOR = 'GET_2FA_LOADING_INDICATOR';

export const ACTIVATE_2FA_REQUEST = 'ACTIVATE_2FA_REQUEST';
export const ACTIVATE_2FA_SUCCESS = 'ACTIVATE_2FA_SUCCESS';
export const ACTIVATE_2FA_FAILURE = 'ACTIVATE_2FA_FAILURE';
export const ACTIVATE_2FA_LOADING_INDICATOR = 'ACTIVATE_2FA_LOADING_INDICATOR';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
export const CHANGE_PASSWORD_LOADING_INDICATOR = 'CHANGE_PASSWORD_LOADING_INDICATOR';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const RESET_PASSWORD_LOADING_INDICATOR = 'RESET_PASSWORD_LOADING_INDICATOR';

export const CONFIRM_RESET_PASSWORD_REQUEST = 'CONFIRM_RESET_PASSWORD_REQUEST';
export const CONFIRM_RESET_PASSWORD_SUCCESS = 'CONFIRM_RESET_PASSWORD_SUCCESS';
export const CONFIRM_RESET_PASSWORD_FAILURE = 'CONFIRM_RESET_PASSWORD_FAILURE';
export const CONFIRM_RESET_PASSWORD_LOADING_INDICATOR =
  'CONFIRM_RESET_PASSWORD_LOADING_INDICATOR';

export const SAVE_TOKEN_REQUEST = 'SAVE_TOKEN_REQUEST';
export const SAVE_TOKEN_SUCCESS = 'SAVE_TOKEN_SUCCESS';
export const SAVE_TOKEN_FAILURE = 'SAVE_TOKEN_FAILURE';
export const SAVE_TOKEN_LOADING_INDICATOR = 'SAVE_TOKEN_LOADING_INDICATOR';

export const GET_CURRENCIES_REQUEST = 'GET_CURRENCIES_REQUEST';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_FAILURE = 'GET_CURRENCIES_FAILURE';
export const GET_CURRENCIES_LOADING_INDICATOR = 'GET_CURRENCIES_LOADING_INDICATOR';

//profile constants
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_PROFILE_LOADING_INDICATOR = 'GET_PROFILE_LOADING_INDICATOR';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'PDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const UPDATE_PROFILE_LOADING_INDICATOR = 'UPDATE_PROFILE_LOADING_INDICATOR';

//transaction constants
export const GET_ALL_TRANSACTIONS_REQUEST = 'GET_ALL_TRANSACTIONS_REQUEST';
export const GET_ALL_TRANSACTIONS_SUCCESS = 'GET_ALL_TRANSACTIONS_SUCCESS';
export const GET_ALL_TRANSACTIONS_FAILURE = 'GET_ALL_TRANSACTIONS_FAILURE';
export const GET_ALL_TRANSACTIONS_LOADING_INDICATOR =
  'GET_ALL_TRANSACTIONS_LOADING_INDICATOR';

export const GET_ONE_TRANSACTION_REQUEST = 'GET_ONE_TRANSACTION_REQUEST';
export const GET_ONE_TRANSACTION_SUCCESS = 'GET_ONE_TRANSACTION_SUCCESS';
export const GET_ONE_TRANSACTION_FAILURE = 'GET_ONE_TRANSACTION_FAILURE';
export const GET_ONE_TRANSACTION_LOADING_INDICATOR =
  'GET_ONE_TRANSACTION_LOADING_INDICATOR';

export const UPDATE_TRANSACTION_REQUEST = 'UPDATE_TRANSACTION_REQUEST';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAILURE = 'UPDATE_TRANSACTION_FAILURE';
export const UPDATE_TRANSACTION_LOADING_INDICATOR =
  'UPDATE_TRANSACTION_LOADING_INDICATOR';

//wallets
export const CRYPTOWALLET_REQUEST = 'CRYPTOWALLET_REQUEST';
export const CRYPTOWALLET_SUCCESS = 'CRYPTOWALLET_SUCCESS';
export const CRYPTOWALLET_FAILURE = 'CRYPTOWALLET_FAILURE';
export const CRYPTOWALLET_LOADING_INDICATOR = 'CRYPTOWALLET_LOADING_INDICATOR';

export const FIATWALLET_REQUEST = 'FIATWALLET_REQUEST';
export const FIATWALLET_SUCCESS = 'FIATWALLET_SUCCESS';
export const FIATWALLET_FAILURE = 'FIATWALLET_FAILURE';
export const FIATWALLET_LOADING_INDICATOR = 'FIATWALLET_LOADING_INDICATOR';
