// Authentication constants
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const FORGOT_PASSWORD_LOADING_INDICATOR = 'FORGOT_PASSWORD_LOADING_INDICATOR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'FAILURE';
export const LOGIN_LOADING_INDICATOR = 'LOGIN_LOADING_INDICATOR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_LOADING_INDICATOR = 'SIGNUP_LOADING_INDICATOR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_LOADING_INDICATOR = 'LOGOUT_LOADING_INDICATOR';

export const GET_OTP_REQUEST = 'GET_OTP_REQUEST';
export const GET_OTP_SUCCESS = 'GET_OTP_SUCCESS';
export const GET_OTP_FAILURE = 'GET_OTP_FAILURE';
export const GET_OTP_LOADING_INDICATOR = 'GET_OTP_LOADING_INDICATOR';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';
export const VERIFY_OTP_LOADING_INDICATOR = 'VERIFY_OTP_LOADING_INDICATOR';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
export const CHANGE_PASSWORD_LOADING_INDICATOR = 'CHANGE_PASSWORD_LOADING_INDICATOR';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const RESET_PASSWORD_LOADING_INDICATOR = 'RESET_PASSWORD_LOADING_INDICATOR';

export const CONFIRM_RESET_PASSWORD_REQUEST = 'CONFIRM_RESET_PASSWORD_REQUEST';
export const CONFIRM_RESET_PASSWORD_SUCCESS = 'CONFIRM_RESET_PASSWORD_SUCCESS';
export const CONFIRM_RESET_PASSWORD_FAILURE = 'CONFIRM_RESET_PASSWORD_FAILURE';
export const CONFIRM_RESET_PASSWORD_LOADING_INDICATOR =
  'CONFIRM_RESET_PASSWORD_LOADING_INDICATOR';

export const ACTIVATE_ACCOUNT_REQUEST = 'ACTIVATE_ACCOUNT_REQUEST';
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS';
export const ACTIVATE_ACCOUNT_FAILURE = 'ACTIVATE_ACCOUNT_FAILURE';
export const ACTIVATE_ACCOUNT_LOADING_INDICATOR =
  'ACTIVATE_ACCOUNT_LOADING_INDICATOR';

export const SAVE_TOKEN_REQUEST = 'SAVE_TOKEN_REQUEST';
export const SAVE_TOKEN_SUCCESS = 'SAVE_TOKEN_SUCCESS';
export const SAVE_TOKEN_FAILURE = 'SAVE_TOKEN_FAILURE';
export const SAVE_TOKEN_LOADING_INDICATOR = 'SAVE_TOKEN_LOADING_INDICATOR';


export const GET_CURRENCIES_REQUEST = 'GET_CURRENCIES_REQUEST';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_FAILURE = 'GET_CURRENCIES_FAILURE';
export const GET_CURRENCIES_LOADING_INDICATOR = 'GET_CURRENCIES_LOADING_INDICATOR';

//profile constants
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_PROFILE_LOADING_INDICATOR = 'GET_PROFILE_LOADING_INDICATOR';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'PDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const UPDATE_PROFILE_LOADING_INDICATOR = 'UPDATE_PROFILE_LOADING_INDICATOR';

//transaction constants
export const GET_ALL_TRANSACTIONS_REQUEST = 'GET_ALL_TRANSACTIONS_REQUEST';
export const GET_ALL_TRANSACTIONS_SUCCESS = 'GET_ALL_TRANSACTIONS_SUCCESS';
export const GET_ALL_TRANSACTIONS_FAILURE = 'GET_ALL_TRANSACTIONS_FAILURE';
export const GET_ALL_TRANSACTIONS_LOADING_INDICATOR =
  'GET_ALL_TRANSACTIONS_LOADING_INDICATOR';

export const GET_ONE_TRANSACTION_REQUEST = 'GET_ONE_TRANSACTION_REQUEST';
export const GET_ONE_TRANSACTION_SUCCESS = 'GET_ONE_TRANSACTION_SUCCESS';
export const GET_ONE_TRANSACTION_FAILURE = 'GET_ONE_TRANSACTION_FAILURE';
export const GET_ONE_TRANSACTION_LOADING_INDICATOR =
  'GET_ONE_TRANSACTION_LOADING_INDICATOR';

export const UPDATE_TRANSACTION_REQUEST = 'UPDATE_TRANSACTION_REQUEST';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAILURE = 'UPDATE_TRANSACTION_FAILURE';
export const UPDATE_TRANSACTION_LOADING_INDICATOR =
  'UPDATE_TRANSACTION_LOADING_INDICATOR';

//wallets
export const GET_CRYPTO_WALLETS_REQUEST = 'GET_CRYPTO_WALLETS_REQUEST';
export const GET_CRYPTO_WALLETS_SUCCESS = 'GET_CRYPTO_WALLETS_SUCCESS';
export const GET_CRYPTO_WALLETS_FAILURE = 'GET_CRYPTO_WALLETS_FAILURE';
export const GET_CRYPTO_WALLETS_LOADING_INDICATOR =
  'GET_CRYPTO_WALLETS_LOADING_INDICATOR';

export const DEPOSIT_NAIRA_REQUEST = 'DEPOSIT_NAIRA_REQUEST';
export const DEPOSIT_NAIRA_SUCCESS = 'DEPOSIT_NAIRA_SUCCESS';
export const DEPOSIT_NAIRA_FAILURE = 'DEPOSIT_NAIRA_FAILURE';
export const DEPOSIT_NAIRA_LOADING_INDICATOR = 'DEPOSIT_NAIRA_LOADING_INDICATOR';

export const SEND_BTC_REQUEST = 'SEND_BTC_REQUEST';
export const SEND_BTC_SUCCESS = 'SEND_BTC_SUCCESS';
export const SEND_BTC_FAILURE = 'SEND_BTC_FAILURE';
export const SEND_BTC_LOADING_INDICATOR = 'SEND_BTC_LOADING_INDICATOR';

export const SEND_ETH_REQUEST = 'SEND_ETH_REQUEST';
export const SEND_ETH_SUCCESS = 'SEND_ETH_SUCCESS';
export const SEND_ETH_FAILURE = 'SEND_ETH_FAILURE';
export const SEND_ETH_LOADING_INDICATOR = 'SEND_ETH_LOADING_INDICATOR';

export const WITHDRAW_NAIRA_REQUEST = 'WITHDRAW_NAIRA_REQUEST';
export const WITHDRAW_NAIRA_SUCCESS = 'WITHDRAW_NAIRA_SUCCESS';
export const WITHDRAW_NAIRA_FAILURE = 'WITHDRAW_NAIRA_FAILURE';
export const WITHDRAW_NAIRA_LOADING_INDICATOR = 'WITHDRAW_NAIRA_LOADING_INDICATOR';

export const SEND_USDT_REQUEST = 'SEND_USDT_REQUEST';
export const SEND_USDT_SUCCESS = 'SEND_USDT_SUCCESS';
export const SEND_USDT_FAILURE = 'SEND_USDT_FAILURE';
export const SEND_USDT_LOADING_INDICATOR = 'SEND_USDT_LOADING_INDICATOR';

// Others
export const UPLOAD_UTILITY_BILL_REQUEST = 'UPLOAD_UTILITY_BILL_REQUEST';
export const UPLOAD_UTILITY_BILL_SUCCESS = 'UPLOAD_UTILITY_BILL_SUCCESS';
export const UPLOAD_UTILITY_BILL_FAILURE = 'UPLOAD_UTILITY_BILL_FAILURE';
export const UPLOAD_UTILITY_BILL_LOADING_INDICATOR =
  'UPLOAD_UTILITY_BILL_LOADING_INDICATOR';

export const GET_SWAP_LIMIT_REQUEST = 'GET_SWAP_LIMIT_REQUEST';
export const GET_SWAP_LIMIT_SUCCESS = 'GET_SWAP_LIMIT_SUCCESS';
export const GET_SWAP_LIMIT_FAILURE = 'GET_SWAP_LIMIT_FAILURE';
export const GET_SWAP_LIMIT_LOADING_INDICATOR = 'GET_SWAP_LIMIT_LOADING_INDICATOR';

export const GET_CURRENCIES_REQUEST = 'GET_CURRENCIES_REQUEST';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_FAILURE = 'GET_CURRENCIES_FAILURE';
export const GET_CURRENCIES_LOADING_INDICATOR = 'GET_CURRENCIES_LOADING_INDICATOR';

export const GET_FAQ_REQUEST = 'GET_FAQ_REQUEST';
export const GET_FAQ_SUCCESS = 'GET_FAQ_SUCCESS';
export const GET_FAQ_FAILURE = 'GET_FAQ_FAILURE';
export const GET_FAQ_LOADING_INDICATOR = 'GET_FAQ_LOADING_INDICATOR';

export const TRADE_REQUEST = 'TRADE_REQUEST';
export const TRADE_SUCCESS = 'TRADE_SUCCESS';
export const TRADE_FAILURE = 'TRADE_FAILURE';
export const TRADE_LOADING_INDICATOR = 'TRADE_LOADING_INDICATOR';

export const VERIFY_BANK_ACCOUNT_REQUEST = 'VERIFY_BANK_ACCOUNT_REQUEST';
export const VERIFY_BANK_ACCOUNT_SUCCESS = 'VERIFY_BANK_ACCOUNT_SUCCESS';
export const VERIFY_BANK_ACCOUNT_FAILURE = 'VERIFY_BANK_ACCOUNT_FAILURE';
export const VERIFY_BANK_ACCOUNT_LOADING_INDICATOR =
  'VERIFY_BANK_ACCOUNT_LOADING_INDICATOR';

// Trade
export const BUY_CRYPTO_REQUEST = 'BUY_CRYPTO_REQUEST';
export const BUY_CRYPTO_SUCCESS = 'BUY_CRYPTO_SUCCESS';
export const BUY_CRYPTO_FAILURE = 'BUY_CRYPTO_FAILURE';
export const BUY_CRYPTO_LOADING_INDICATOR = 'BUY_CRYPTO_LOADING_INDICATOR';

export const SELL_CRYPTO_REQUEST = 'SELL_CRYPTO_REQUEST';
export const SELL_CRYPTO_SUCCESS = 'SELL_CRYPTO_SUCCESS';
export const SELL_CRYPTO_FAILURE = 'SELL_CRYPTO_FAILURE';
export const SELL_CRYPTO_LOADING_INDICATOR = 'SELL_CRYPTO_LOADING_INDICATOR';

export const SWAP_CRYPTO_REQUEST = 'SWAP_CRYPTO_REQUEST';
export const SWAP_CRYPTO_SUCCESS = 'SWAP_CRYPTO_SUCCESS';
export const SWAP_CRYPTO_FAILURE = 'SWAP_CRYPTO_FAILURE';
export const SWAP_CRYPTO_LOADING_INDICATOR = 'SWAP_CRYPTO_LOADING_INDICATOR';

